// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXKkGNVDjlaDrMW8XBx99Oul0E2honnCk',
    appId: '1:986531705132:web:17b609c03dcce8ce913c89',
    messagingSenderId: '986531705132',
    projectId: 'diet-app-23456',
    authDomain: 'diet-app-23456.firebaseapp.com',
    storageBucket: 'diet-app-23456.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgrrHa01i02nOj7i5zBN5AKMBvB1hQv7k',
    appId: '1:986531705132:android:df9ebd37d9f48248913c89',
    messagingSenderId: '986531705132',
    projectId: 'diet-app-23456',
    storageBucket: 'diet-app-23456.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4zA8N9hffpQ5PQXBRBm6nfKamr0jjgT8',
    appId: '1:986531705132:ios:e06dfa8a328a224b913c89',
    messagingSenderId: '986531705132',
    projectId: 'diet-app-23456',
    storageBucket: 'diet-app-23456.firebasestorage.app',
    iosBundleId: 'com.zuzannaczyzowska.dietApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4zA8N9hffpQ5PQXBRBm6nfKamr0jjgT8',
    appId: '1:986531705132:ios:9144e809e4f353d1913c89',
    messagingSenderId: '986531705132',
    projectId: 'diet-app-23456',
    storageBucket: 'diet-app-23456.firebasestorage.app',
    iosBundleId: 'com.example.dietApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXKkGNVDjlaDrMW8XBx99Oul0E2honnCk',
    appId: '1:986531705132:web:d89cd2a7309acfa7913c89',
    messagingSenderId: '986531705132',
    projectId: 'diet-app-23456',
    authDomain: 'diet-app-23456.firebaseapp.com',
    storageBucket: 'diet-app-23456.firebasestorage.app',
  );
}
